# Generated by Django 4.2.7 on 2023-12-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=50)),
                ('v_quantity', models.IntegerField()),
                ('v_discount', models.IntegerField()),
            ],
        ),
    ]
