# Generated by Django 4.2.7 on 2023-12-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
