# Generated by Django 4.2.7 on 2023-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_desc", models.TextField()),
                ("product_price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("product_quantity", models.IntegerField(default=0)),
                ("product_category", models.CharField(max_length=100)),
                ("product_image", models.ImageField(null=True, upload_to="")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
