# Generated by Django 4.2.7 on 2023-12-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="sold_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
