# Generated by Django 4.2.7 on 2023-12-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_products_sold_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="promotion",
            field=models.BooleanField(default=False),
        ),
    ]
