# Generated by Django 4.2.7 on 2023-12-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_products_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="product_price_on_sale",
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
