# Generated by Django 4.2.7 on 2023-12-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0004_products_product_price_on_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promote_name", models.CharField(max_length=100)),
                ("discount", models.IntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("status", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="product", to="product.products"
                    ),
                ),
            ],
        ),
    ]
