# Generated by Django 4.2.7 on 2023-12-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderdetails",
            old_name="total_quantity_choose",
            new_name="quantity",
        ),
    ]
